// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_logs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeliveryLog = `-- name: InsertDeliveryLog :exec
INSERT INTO event_delivery_logs (
    event_id,
    status,
    attempt,
    error_message
) VALUES (
    $1, $2, $3, $4
)
`

type InsertDeliveryLogParams struct {
	EventID      string
	Status       string
	Attempt      int32
	ErrorMessage pgtype.Text
}

func (q *Queries) InsertDeliveryLog(ctx context.Context, arg InsertDeliveryLogParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryLog,
		arg.EventID,
		arg.Status,
		arg.Attempt,
		arg.ErrorMessage,
	)
	return err
}
