// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id, type, payload, created_at, whatsapp_message_id, from_number, command, status, updated_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.WhatsappMessageID,
		&i.FromNumber,
		&i.Command,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByWhatsappMessageID = `-- name: GetEventByWhatsappMessageID :one
SELECT id, type, payload, created_at, whatsapp_message_id, from_number, command, status, updated_at
FROM events
WHERE whatsapp_message_id = $1
`

func (q *Queries) GetEventByWhatsappMessageID(ctx context.Context, whatsappMessageID pgtype.Text) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByWhatsappMessageID, whatsappMessageID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.WhatsappMessageID,
		&i.FromNumber,
		&i.Command,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id,
    whatsapp_message_id,
    from_number,
    command,
    payload,
    status,
    created_at,
    updated_at
  )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEventParams struct {
	ID                string
	WhatsappMessageID pgtype.Text
	FromNumber        pgtype.Text
	Command           pgtype.Text
	Payload           string
	Status            pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.WhatsappMessageID,
		arg.FromNumber,
		arg.Command,
		arg.Payload,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, type, payload, created_at, whatsapp_message_id, from_number, command, status, updated_at
FROM events
ORDER BY created_at ASC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.WhatsappMessageID,
			&i.FromNumber,
			&i.Command,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events
SET status = $2,
  updated_at = NOW()
WHERE id = $1
`

type UpdateEventStatusParams struct {
	ID     string
	Status pgtype.Text
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventStatus, arg.ID, arg.Status)
	return err
}
