// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByID = `-- name: GetEventByID :one
SELECT id,
  type,
  payload,
  created_at,
  processed
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.Processed,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, type, payload, created_at, processed)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	ID        string
	Type      string
	Payload   string
	CreatedAt pgtype.Timestamp
	Processed pgtype.Bool
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
		arg.Processed,
	)
	return err
}

const listUnprocessedEvents = `-- name: ListUnprocessedEvents :many
SELECT id,
  type,
  payload,
  created_at,
  processed
FROM events
WHERE processed = FALSE
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnprocessedEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUnprocessedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessed = `-- name: MarkProcessed :exec
UPDATE events
SET processed = TRUE
WHERE id = $1
`

func (q *Queries) MarkProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markProcessed, id)
	return err
}
