// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :execrows
INSERT INTO idempotency_keys (key, event_id, expires_at, metadata)
VALUES ($1, $2, $3, $4) ON CONFLICT (key) DO NOTHING
`

type CreateIdempotencyKeyParams struct {
	Key       string
	EventID   string
	ExpiresAt pgtype.Timestamp
	Metadata  []byte
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.Key,
		arg.EventID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, event_id, created_at, expires_at, metadata
FROM idempotency_keys
WHERE key = $1
  AND expires_at > NOW()
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.EventID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getIdempotencyKeyStats = `-- name: GetIdempotencyKeyStats :one
SELECT COUNT(*) as total_keys,
  COUNT(
    CASE
      WHEN expires_at > NOW() THEN 1
    END
  ) as active_keys,
  COUNT(
    CASE
      WHEN expires_at <= NOW() THEN 1
    END
  ) as expired_keys
FROM idempotency_keys
`

type GetIdempotencyKeyStatsRow struct {
	TotalKeys   int64
	ActiveKeys  int64
	ExpiredKeys int64
}

func (q *Queries) GetIdempotencyKeyStats(ctx context.Context) (GetIdempotencyKeyStatsRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyStats)
	var i GetIdempotencyKeyStatsRow
	err := row.Scan(&i.TotalKeys, &i.ActiveKeys, &i.ExpiredKeys)
	return i, err
}
