// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        string
	Type      string
	Payload   string
	CreatedAt pgtype.Timestamp
	Status    pgtype.Text
	UpdatedAt pgtype.Timestamp
	TraceID   pgtype.Text
	Priority  pgtype.Text
}

type EventDeliveryLog struct {
	ID           int32
	EventID      string
	Status       string
	Attempt      int32
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type IdempotencyKey struct {
	Key       string
	EventID   string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	Metadata  []byte
}
