// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        string
	Type      string
	Payload   string
	CreatedAt pgtype.Timestamp
	Processed pgtype.Bool
}
